defaultBaseImage: public.ecr.aws/eks-distro-build-tooling/eks-distro-minimal-base-nonroot:2022-07-27-1658910674.2
builds:
- env:
  - CGO_ENABLED=0
  flags:
  - -mod=readonly
  ldflags:
  - -s
  - -w
  - -X github.com/pjtatlow/aws-load-balancer-controller/pkg/version.GitVersion={{.Env.GIT_VERSION}}
  - -X github.com/pjtatlow/aws-load-balancer-controller/pkg/version.GitCommit={{.Env.GIT_COMMIT}}
  - -X github.com/pjtatlow/aws-load-balancer-controller/pkg/version.BuildDate={{.Env.BUILD_DATE}}

